---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: production
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  acme:
    email: workquark@gmail.com
    privateKeySecretRef:
      name: cloud-dns-letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory    
    solvers:
