global:
  zone: kubecost.druidsoft.in  # cluster.local

ingress:
  enabled: true
  # className: nginx
  labels:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  annotations:
      kubernetes.io/ingress.allow-http: "false"
      # kubernetes.io/ingress.global-static-ip-name: global-static-ip
      external-dns.alpha.kubernetes.io/hostname: kubecost.druidsoft.in
      cert-manager.io/cluster-issuer: production
  paths: ["/"]  # There's no need to route specifically to the pods-- we have an nginx deployed that handles routing
  pathType: ImplementationSpecific
  hosts:
    - kubecost.druidsoft.in
  tls: 
   - secretName: cost-analyzer-tls
     hosts:
       - kubecost.druidsoft.in

service:
  type: NodePort
  annotations: 
    cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "kubecost-service-neg"}}}'