# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World! This is great place to live ! 
  REGION: "europe-west1"
  TWINGATE_ADMIN_GROUP_ID: "R3JvdXA6MzM3NDAx"
  TWINGATE_API_TOKEN: "vVY_Y_X0IHjECCprQVywjiw4FvWvYusisNIzTzU9xCBkxacR79SKQaTLKkgQTfc9e0ad5kRXGJgiGDQWDUxF8syN7dCg3K-GOZ4prkoZwgDj1Se2tyRlmyfgKOGYUTleWaxmSg"
  PROJECT: 
    sh: gcloud config get project
  AUTH_TOKEN: 
    sh: gcloud auth print-access-token

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  plan_all:
    env:
      TF_VAR_region: "{{ .REGION }}"
      TF_VAR_project_id: "{{ .PROJECT }}"
      TF_VAR_auth_token: "{{ .AUTH_TOKEN }}"
      TF_VAR_twingate_admin_group_id: "{{ .TWINGATE_ADMIN_GROUP_ID }}"
      TF_VAR_twingate_api_token: "{{ .TWINGATE_API_TOKEN }}"
    cmds:
      - echo "{{.TF_VAR_project_id}}"
      - terraform init
      - terraform plan
      - terraform output
    # silent: true

  apply_all:
    cmds:
      - terraform apply -auto-approve
    # silent: true

  destroy:
    cmds:
      - terraform destroy -auto-approve
      
  destroy_all:
    cmds:
      - helm uninstall --wait argocd -n argocd
      - terraform destroy -auto-approve
