# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  TF_VAR_region: "europe-west1"
  TF_VAR_project_id: 
    sh: gcloud config get project
  TF_VAR_auth_token: 
    sh: gcloud auth print-access-token

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  plan:
    cmds:
      - echo "Auth Token - {{.TF_VAR_auth_token}}"
      - terraform init
      - terraform plan
      - terraform output
    # silent: true

  apply_all:
    cmds:
      - terraform apply -auto-approve
    # silent: true

  destroy:
    cmds:
      - terraform destroy -auto-approve
      
  destroy_all:
    cmds:
      - helm uninstall --wait argocd -n argocd
      - terraform destroy -auto-approve
