redis-ha:
  enabled: true

controller:
  replicas: 1

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2

global:
  domain: argocd.druidsoft.in

configs:
  params:
    server.insecure: true

server:
  service:
    type: NodePort
    # -- Server service annotations
    annotations:
      cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "argocd-service-neg"}}}'
  autoscaling:
    enabled: true
    minReplicas: 2
  ingress:
    enabled: true
    # ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      kubernetes.io/ingress.global-static-ip-name: "global-static-ip"
      # kubernetes.io/ingress.class: "gce"
    # extraTls:
    #   - hosts:
    #     - argocd.druidsoft.in
    #     secretName: argocd-ssl-tls