---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubecost
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-kubecost'      
    spec:
      project: '{{name}}'
      syncPolicy:        
        retry:
          limit: 3 # number of failed sync attempt retries; unlimited number of attempts if less than 0
          backoff:
            duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
            factor: 2 # a factor to multiply the base duration after each failed retry
            maxDuration: 5s # the maximum amount of time allowed for the backoff strategy
        syncOptions:
          - CreateNamespace=true
          - FailOnSharedResource=true
        automated:
          prune: true
          selfHeal: true
      sources:
        - repoURL: https://github.com/Workquark/Terraform.git
          ref: argo
        - repoURL: https://kubecost.github.io/cost-analyzer/
          chart: cost-analyzer
          targetRevision: 2.7.0
          helm:
            valueFiles:
            - $argo/k8s/argocd/gcp/manifests/helmcharts/kubecost/{{name}}.values.yaml
      destination:
        server: '{{server}}'
        namespace: kubecost