apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/part-of: argocd
    argocd.argoproj.io/secret-type: repository
  name: strimzi-kafka-oci-secret
  namespace: argocd
type: Opaque
stringData:
  url: quay.io/strimzi-helm/strimzi-kafka-operator
  name: strimzi-kafka
  type: helm
  enableOCI: "true"