apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: docker-io-helm-oci
  namespace: argocd
stringData:
  url: quay.io/strimzi-helm/strimzi-kafka-operator
  name: strimzi-kafka
  type: helm
  enableOCI: "true"